services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: shopivers-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: spring_weave
    ports:
      - "5432:5432"
    volumes:
      - shopivers_db_data:/var/lib/postgresql/data
      - ./database_creation_script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shopivers_network

  # Interface graphique PgAdmin pour PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: shopivers-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopivers.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shopivers_network

  # Application Spring Boot
  backend:
    image: spring-weave:latest
    container_name: shopivers-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring_weave
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shopivers_network

volumes:
  shopivers_db_data:

networks:
  shopivers_network:
    driver: bridge
