CREATE TYPE "user_role" AS ENUM (
  'client',
  'vendeur',
  'livreur',
  'admin'
);

CREATE TYPE "account_status" AS ENUM (
  'actif',
  'bloque',
  'en_attente'
);

CREATE TYPE "order_status" AS ENUM (
  'panier',
  'payee',
  'en_preparation',
  'expediee',
  'livree',
  'annulee',
  'litige'
);

CREATE TYPE "credit_status" AS ENUM (
  'demande',
  'approuve',
  'refuse',
  'rembourse'
);

CREATE TYPE "dispute_status" AS ENUM (
  'ouvert',
  'en_cours',
  'resolu_client',
  'resolu_vendeur'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "nom_complet" varchar,
  "telephone" varchar,
  "adresse" text,
  "role" user_role NOT NULL,
  "statut" account_status DEFAULT 'en_attente',
  "created_at" timestamp
);

CREATE TABLE "vendors" (
  "user_id" integer PRIMARY KEY,
  "nom_boutique" varchar,
  "siret" varchar,
  "documents_verifies" boolean DEFAULT false,
  "solde_portefeuille" decimal(10,2)
);

CREATE TABLE "drivers" (
  "user_id" integer PRIMARY KEY,
  "type_vehicule" varchar,
  "zone_geographique" varchar,
  "est_disponible" boolean,
  "localisation_gps" point
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "parent_id" integer
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vendor_id" integer,
  "category_id" integer,
  "titre" varchar,
  "description" text,
  "prix" decimal(10,2),
  "stock" integer,
  "image_url" varchar
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" integer,
  "date_commande" timestamp,
  "statut" order_status,
  "total_ttc" decimal(10,2)
);

CREATE TABLE "order_items" (
  "order_id" integer,
  "product_id" integer,
  "quantite" integer,
  "prix_unitaire" decimal(10,2),
  "note_client" integer,
  "commentaire_client" text
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "montant" decimal(10,2),
  "date_paiement" timestamp,
  "methode" varchar,
  "est_echelonne" boolean
);

CREATE TABLE "payment_schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" integer,
  "date_prevue" date,
  "montant" decimal(10,2),
  "est_paye" boolean
);

CREATE TABLE "deliveries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "driver_id" integer,
  "date_prise_charge" timestamp,
  "date_livraison_reelle" timestamp,
  "signature_reception" varchar,
  "incident_signale" boolean
);

CREATE TABLE "micro_credits" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" integer,
  "montant_demande" decimal(10,2),
  "taux_interet" decimal(5,2),
  "duree_mois" integer,
  "statut" credit_status,
  "date_demande" timestamp,
  "date_validation" timestamp
);

CREATE TABLE "disputes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "createur_id" integer,
  "motif" varchar,
  "description" text,
  "statut" dispute_status,
  "date_creation" timestamp
);

CREATE TABLE "dispute_proofs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dispute_id" integer,
  "fichier_url" varchar,
  "type_fichier" varchar
);

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "vendors" ("user_id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "drivers" ("user_id");

ALTER TABLE "products" ADD FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("user_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "payment_schedules" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("id") REFERENCES "deliveries" ("order_id");

ALTER TABLE "deliveries" ADD FOREIGN KEY ("driver_id") REFERENCES "drivers" ("user_id");

ALTER TABLE "micro_credits" ADD FOREIGN KEY ("users_id") REFERENCES "vendors" ("user_id");

ALTER TABLE "disputes" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "disputes" ADD FOREIGN KEY ("createur_id") REFERENCES "users" ("id");

ALTER TABLE "dispute_proofs" ADD FOREIGN KEY ("dispute_id") REFERENCES "disputes" ("id");
