# Nom de l'application
spring.application.name=shopiverse-backend

# Connexion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopiverse_db
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate (Spring va créer les tables tout seul !)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect