spring.application.name=spring-weave
spring.datasource.url=jdbc:postgresql://localhost:5452/spring_weave
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
